# Header
navbar_brand: <img src="/image/logo.png" />
menu:
  Home: index.html
  Archives: archives/
rss: /atom.xml

# Content
excerpt_link: Read More
fancybox: false
favicon: /image/logo.png

# Sidebar
widgets:
- about
- friends
- recent_posts
- category
- archive

# widget behavior
archive_type: 'monthly'
show_count: true
